### ISSUE TITLE
Tracking component

### ISSUE THREAD

**Issue by lougroshek** [Hyperobjekt/cpal-components#28]
Implement a tracking component that presumes and accesses a parent dataLayer array and pushes explorer events to the array.

**Comment by amygroshek** [comment]
Will use this, and pass the handler *into* the explorer: https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/

**Comment by amygroshek** [comment]
Explorer events to capture:

- [ ] share (all types of share, store the type as well as event)
- [ ] view select (map or feeder)
- [ ] metric update (metric selected)
- [ ] layers update (layers selected)
- [ ] school search feeder view (school searched, SLN, school name, possibly feeder)
- [ ] school search map (School searched by SLN and name)
- [ ] feeder click (feeder clicked)
- [ ] school hover (in map)
- [ ] school hover (in feeder distribution chart)
- [ ] zoom (new zoom level) ?
- [ ] pan (coords) ? 
- [ ] reset of map view
- [ ] map screen capture
- [ ] error

**Comment by lougroshek** [comment]
- [ ] Test when loaded into parent site
